SOURCES = \
CreateRico.cpp \
gsl.cpp \
MyVector.cpp \
PowerOfSums.cpp \
ProductDigester.cpp \
rcinterface.cpp \
RicoAdd.cpp \
RicoBasicRV.cpp \
RicoBeta.cpp \
RicoCauchy.cpp \
RicoChiSquared.cpp \
Rico.cpp \
RicoDivide.cpp \
RicoDouble.cpp \
RicoExp.cpp \
RicoExponential.cpp \
RicoFisher.cpp \
RicoFraction.cpp \
RicoFunction.cpp \
RicoInteger.cpp \
RicoLog.cpp \
RicoLogistic.cpp \
RicoLogNormal.cpp \
RicoMultiply.cpp \
RicoNegate.cpp \
RicoNormal.cpp \
RicoNumber.cpp \
RicoPower.cpp \
RicoRegistry.cpp \
RicoSimplify.cpp \
RicoSqrt.cpp \
RicoStudents_t.cpp \
RicoSubtract.cpp \
RicoTriangular.cpp \
RicoUniform.cpp \
RicoWeibull.cpp \
stl.cpp \
SumDigester.cpp \
SumProductMatrix.cpp \
TestRico.cpp \
Util.cpp \
X.cpp \
X_main.cpp \
